routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('location', 'LocationController');

Route::get('/', function(){
    return redirect('location');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LocationRequest;
use App\Model\Location;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class LocationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            $data = Location::all();

            return response()->json($data, 200);
        } else {
            $uri = Route::current()->uri;

            return view('create-location', compact('uri'));
        }
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LocationRequest $request)
    {
           $data = Location::create([
               'name' => $request['name'],
               'lat' => $request['lat'],
               'lng' => $request['lng']
           ]);

        return response()->json($data, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function show(Location $location)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Location::findOrFail($id);

        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function update(LocationRequest $request, $id)
    {
        Location::find($id)
            ->update([
                'name' => $request['name'],
                'lat' => $request['lat'],
                'lng' => $request['lng']
            ]);

        return response()->json(["valid" => true], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Location  $location
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Location::destroy($id);

        return response()->json($data, 200);
    }
}

app/Http/Controllers/MapController.php
<?php

namespace App\Http\Controllers;

use App\Model\Location;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class MapController extends Controller
{

    public function getMap(Request $request){

        if ($request->ajax()) {
            $data = Location::all();

            return response()->json($data, 200);
        } else {
            $uri = Route::current()->uri;

            return view('map', compact('uri'));
        }
    }


}

resources/views/create-location.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="uri" content="/{{$uri}}">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfMLa2ebRhygx_1ICEDdTjpBVJ4yxFplM"></script>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href=" {{ asset("assets/plugins/font-awesome/css/font-awesome.min.css") }}">

s

    <!--Toastr-->
    <link href="{{asset('assets/plugins/toastr/build/toastr.css')}}" rel="stylesheet">
</head>



<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Gmap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Cargar Ubicaciones<span class="sr-only">(current)</span></a>
                </li>
                
            </ul>
        </div>
    </nav>

    <div class="container-fluid" style="margin-top: 25px; margin-bottom: 50px">

            <div class="col-3">
                <div class="card">
                    <div class="card-header">
                        Guardar Ubicación
                    </div>
                    <div class="card-body">
                        <form id="form-create" role="form" accept-charset="UTF-8" enctype="multipart/form-data">
                            <input type="hidden" name="_token" value="{{csrf_token()}}" id="token-create" />
                            <div class="form-group">
                                <label for="exampleInputEmail1">Nombre</label>
                                <input type="text" class="form-control" name="name" id="name" aria-describedby="emailHelp">
                                <small class="pull-left" style="font-size: 11px;color: #ff6d5e;" id="error-name"></small>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Latitud</label>
                                <input type="text" id="txtLat" class="form-control" style="color:red" name="lat"  aria-describedby="emailHelp">
                                <small class="pull-left" style="font-size: 11px;color: #ff6d5e;" id="error-lat"></small>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputEmail1">Longitud</label>
                                <input type="text" id="txtLng" class="form-control" style="color:red" name="lng"  aria-describedby="emailHelp">
                                <small class="pull-left" style="font-size: 11px;color: #ff6d5e;" id="error-lng"></small>
                            </div>
                            <div class="text-center">
                                <button type="button" class="btn btn-outline-primary" id="btn-ubications">Ubicaciones</button>
                                <button type="submit" class="btn btn-primary" id="btn-create">Guardar</button>
                                <button type="button" class="btn btn-primary  btn-primary " id="btn-preload-create"  style="display: none"><i class="fa fa-spinner fa-spin" style="font-size:18px;color:white"></i> Guardando..</button>
                            </div>
                        </form>
                    </div>
                </div>


            </div>
            <div class="col-9" >
                <div id="map_canvas" style="width: auto; height: 600px;"></div>
            </div>

        </div>
   


        </div>
    </div>

    <!--MODAL EDIT-->



    <!--Toastr-->
    <script src="{{asset('assets/plugins/toastr/toastr.js')}}"></script>

    
    <script src="{{asset('assets/js/main.js')}}"></script>


</body>
</html>

resources/views/map.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="uri" content="/{{$uri}}">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfMLa2ebRhygx_1ICEDdTjpBVJ4yxFplM"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Gmap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{route('location.index')}}">Cargar Ubicaciones<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Ver Mapa</a>
            </li>
        </ul>
    </div>
</nav>


        <div class="col-12" >
            <div id="map_canvas" style="width: auto; height: 600px;"></div>
        </div>


<script src="{{asset('assets/js/map.js')}}"></script>

</body>
</html>

resources/views/modals/edit.blade.php
@section('edit')
    <div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header bg-green text-black-50">
                    <h5 class="modal-title" id="exampleModalLabel">Editar</h5>
                    <button type="button" class="close close-edit" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="form-edit" role="form" accept-charset="UTF-8" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="PUT">
                    <input type="hidden"  value="" id="id-edit">
                    <input type="hidden" name="_token" value="{{csrf_token()}}" id="token-edit" />
                    <div class="modal-body">
                        <div class="row">
                            <div class="form-group col-12">
                                <label for="recipient-name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" name="name" id="name-edit">
                                <small class="pull-left" style="font-size: 11px;color: #ff6d5e;" id="error-name-edit"></small>
                                <div class="validation"><small style="color: #ff6d5e;">{{$errors->first('name')}}</small></div>
                            </div>
                            <div class="form-group col-12">
                                <label for="recipient-name" class="col-form-label">Latitud:</label>
                                <input type="text" class="form-control" name="lat" id="lat-edit">
                                <small class="pull-left" style="font-size: 11px;color: #ff6d5e;" id="error-lat-edit"></small>
                                <div class="validation"><small style="color: #ff6d5e;">{{$errors->first('lat')}}</small></div>
                            </div>
                            <div class="form-group col-12">
                                <label for="recipient-name" class="col-form-label">Longitud:</label>
                                <input type="text" class="form-control" name="lng" id="lng-edit">
                                <small class="pull-left" style="font-size: 11px;color: #ff6d5e;" id="error-lng-edit"></small>
                                <div class="validation"><small style="color: #ff6d5e;">{{$errors->first('lng')}}</small></div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="col-xs-12">
                            <button type="button" class="btn btn-secondary" id="btn-close-edit" data-dismiss="modal">Cerrar</button>
                            <button type="button" class="btn btn-primary  btn-primary " id="btn-preload-edit"  style="display: none"><i class="fa fa-spinner fa-spin" style="font-size:18px;color:white"></i> Actualizando..</button>
                            <button type="submit" class="btn btn-primary" id="btn-edit">Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@show